SELECT
'<DC_RELEASE>',
e.DC_SOURCE,
e.DC_SUSPECTFLAG,
'<DC_TIMEZONE>',
e.ENodeBFunction,
e.ERBS,
e.MOID,
e.NESW,
e.OSS_ID,
e.PERIOD_DURATION,
<COUNTERS>
e.ROWSTATUS,
e.SESSION_ID,
e.SN,
e.TIMELEVEL,
<MINUTE>,
<HOUR>,
<DAY>,
<MONTH>,
<YEAR>,
'<DATE>',
'<UTC_DATETIME_ID>',
'<DATETIME_ID>'
FROM <TABLE> e
INNER JOIN DC_E_ERBS_CAPACITYCONNECTEDUSERS_RAW c
ON e.ERBS=c.ERBS AND e.DATETIME_ID=c.DATETIME_ID
WHERE e.datetime_id = dateadd(dd, days('<DATE>', '<BASE_DATE>') + <DAY> - 1, '<DATETIME_ID>')
  AND c.ERBS LIKE '<NODES_TO_MATCH>';
OUTPUT TO ETL/<TABLE>/data.csv
ESCAPES OFF
DELIMITED BY '|'
QUOTE '' ALL

